### ISSUE TITLE
[Jour1/42alternatif] Point de départ

### ISSUE THREAD

**Issue by slequeux** [manuqcr/loire_velo#1]
Pourquoi le départ est au sud de la Loire alors que la gare est nord Loire ?

**Comment by ghost** [comment]
Le départ est depuis la gare des Aubray, toujours desservie par les trains contrairement à la gare d'Orléans pour laquelle il faut souvent faire un changement. Cf l'aller dans l'onglet 2 du google doc.

**Comment by slequeux** [comment]
Mais ces deux gares sont nord Loire, non ?

**Comment by EQuincerot** [comment]
Oui comme tu peux le voir ici : http://umap.openstreetmap.fr/fr/map/la-loire-a-velo_156247#14/47.9113/1.9081

**Comment by ghost** [comment]
Ah ok, je comprends. En fait le dossier `alternative` est un dossier exclu. C'est un peu le dossier poubelle pour les itinéraires officiels qui ne conviennent pas. Il pourrait s'appeler `ignore`.

C'est alternative dans le sens ou il existe d'autres chemins mais ce ne sont pas ceux qu'on choisit.
De toute façon le bilan du parcours, c'est sur http://umap.openstreetmap.fr/fr/map/la-loire-a-velo_156247

Je te laisse fermer cette demande.
