### ISSUE TITLE
[Jour4/57] D961

### ISSUE THREAD

**Issue by slequeux** [manuqcr/loire_velo#10]
Attention, si on peut éviter la D961 à la fin en passant par de petites routes, ça serait bien. les gens roulent comme des malades sur cette route.

**Comment by ghost** [comment]
J'ai regardé, geovelo refuse de me faire passer par un chemin qui coupe.
Un finish comme ça : https://goo.gl/maps/QYcvzPHXmhm ?
Bon par contre je ne trouve aucun export gpx depuis google, ça va se finir dans openrunner si ça continue.

Note pour quand je referai le parcours (pour avoir le point de départ exact) : le 57 c'est celui là : https://www.eurovelo6-france.com/etapes/la-dagueniere-bouchemaine

**Comment by slequeux** [comment]
Ok pour ce finish, beaucoup mieux

**Comment by ghost** [comment]
Traité. Au passage : 
- les merges générés par buildAll.groovy sont commités dans github
- uMap n'utilise plus un fichier uploadé à la main mais les différents fichiers generated dans le master de ce repo github (plus facile à mettre à jour)
