### ISSUE TITLE
[Jour5/60] D961

### ISSUE THREAD

**Issue by slequeux** [manuqcr/loire_velo#11]
Idem que #10, éviter au possible la D961. Je propose plutôt de passer par Villemoisan avant Champtocé. ça sera plus tranquille même si un poil plus long.

**Comment by ghost** [comment]
Geovelo et google me font soit passer par la D961 soit par la D104 (qui est plus sinueuse).
https://www.geovelo.fr/france/itinerary/search?profile=MEDIAN&bikeType=TRADITIONAL&wayPoints=47.498358,-0.80698%7C47.475912,-0.84938%7C47.357131,-1.015158

**C'est mieux ça ?** (+3 à 4km que l'itinéraire de base, c'est pas mal)

_Note : Le 60 c'est celui là (utile pour reprendre le même point d'arrivée) : https://www.eurovelo6-france.com/etapes/chalonnes-sur-loire-st-florent-le-vieil_
