### ISSUE TITLE
[Jour5/60] Bord de Loire

### ISSUE THREAD

**Issue by slequeux** [manuqcr/loire_velo#12]
Pourquoi l'éloignement de la Loire ? une raison particulière que je ne vois pas ?

**Comment by ghost** [comment]
Sur le tronçon en face d'Ingrandes ? pour éviter la départementale en bord de Loire je présume.
Mais on peut couper un peu plus : 
https://www.geovelo.fr/france/itinerary/search?profile=MEDIAN&bikeType=TRADITIONAL&wayPoints=47.498358,-0.80698%7C47.475912,-0.84938%7C47.387019,-0.914526%7C47.357131,-1.015158

**Comment by slequeux** [comment]
Ok, comme tu le sens

**Comment by ghost** [comment]
Faisons l'itinéraire du lien ci-dessus
