### ISSUE TITLE
[Jour5/61] Bord de Loire

### ISSUE THREAD

**Issue by slequeux** [manuqcr/loire_velo#13]
Au niveau de "la rabotière", ça serait plus court de longer la Loire, non ? (et probablement moins de montées ^^)

**Comment by ghost** [comment]
Oui longer par la Loire n'est pas l'itinéraire de l'eurovelo mais c'est ce que recommande geovelo.fr :
https://www.geovelo.fr/france/itinerary/search?profile=MEDIAN&bikeType=TRADITIONAL&wayPoints=47.36108,-1.035461%7C47.357119,-1.173827
=> Il faudra couper le fichier gpx de eurovelo pour garder que la partie après le Fourneau

**Comment by ghost** [comment]
:warning: ne pas traiter cette demande sans avoir décidé pour #14

**Comment by slequeux** [comment]
fixed with #14
