### ISSUE TITLE
[Jour5/61] Champtoceaux

### ISSUE THREAD

**Issue by slequeux** [manuqcr/loire_velo#14]
Si y'a moyen de ne pas traverser la Loire deux fois, ça permettrait d'arriver au niveau de Champtoceaux, la ville est plutôt sympa, mais ça fait une grosse cote à se taper si on vient de Oudon

**Comment by ghost** [comment]
On ne montait pas dans Champtoceaux si tu regardes bien la carte (je vais essayer de passer à un fond de carte IGN, pour voir les courbes de niveau, mais ça semble être buggué en ce moment) : http://umap.openstreetmap.fr/fr/map/la-loire-a-velo_156247#16/47.3378/-1.2839

Sinon on pourrait faire ça (mais du coup ça nous ajoute une côte, contraire à ton objectif :smile: ) :
https://www.geovelo.fr/france/itinerary/search?profile=MEDIAN&bikeType=TRADITIONAL&wayPoints=47.36108,-1.035461%7C47.337339,-1.263471
Et dans ce cas, une fois qu'on repart de Champtoceaux, on pourrait aller à Oudon rapidement si la ville vaut le coup. Si on fait quelque chose, traiter #13 en même temps

**Que préfères tu ?**

**Comment by slequeux** [comment]
Oudon, ça ne vaut pas le coup d'y aller. Par contre, voir la ville depuis l'autre côté de la Loire (Champtoceaux ou au niveau du moulin - vers le pont) c'est vraiment sympa.

**Comment by ghost** [comment]
Dans ce cas, comme tu sembles savoir de quoi tu parles, je te laisse préparer cet itinéraire (tu peux partir de ma suggeestion ci-dessus) et marquer le moulin ou l'endroit important à voir sur umap.
Si oudon ne vaut pas le coup, je te laisse retirer le repère château à Oudon.
