### ISSUE TITLE
[Jour5/63] Fin de journée

### ISSUE THREAD

**Issue by slequeux** [manuqcr/loire_velo#15]
Dans l'idée, j'irai bien vers chez mes potes direct (vers La Beaujoire) et si on veut aller en centre ville, on ira en tram ou voiture ^^

**Comment by ghost** [comment]
Du coup tronquer le fichier 63 pour finir par ce parcours : 
https://www.geovelo.fr/nantes/itinerary/search?profile=MEDIAN&bikeType=TRADITIONAL&wayPoints=47.262514,-1.435776%7C47.258857,-1.525984
