### ISSUE TITLE
[Jour6/64] Quelle rive ?

### ISSUE THREAD

**Issue by slequeux** [manuqcr/loire_velo#16]
Le début, en passant par le hangar a bananes et Trentemoult, c'est super ! j'approuve
Mais j'ai un doute sur la traversée du pont de St Nazaire à vélo, ça me parait dangereux.

Et si on veut éviter ce pont, faut rester direct au nord Loire.

**Comment by ghost** [comment]
A voir, on peut faire ça aussi : 
https://www.geovelo.fr/nantes/itinerary/search?profile=MEDIAN&bikeType=TRADITIONAL&wayPoints=47.258857,-1.525984%7C47.321836,-2.094955%7C47.273498,-2.213848
Mais on n'est plus sûr d'aller à St Nazaire, ce point est en suspens.

**Comment by slequeux** [comment]
si airbnb validé : https://www.geovelo.fr/nantes/itinerary/search?profile=MEDIAN&bikeType=TRADITIONAL&wayPoints=47.256023,-1.524675%7C47.199861,-1.573877%7C47.195253,-1.581452%7C47.194145,-1.676102%7C47.261728,-1.786737%7C47.31721,-1.943851%7C47.306735,-1.97196%7C47.309238,-1.984041%7C47.310082,-1.985435%7C47.317763,-2.007236%7C47.316017,-2.075043%7C47.303913,-2.164307%7C47.302006,-2.171838%7C47.299475,-2.181365%7C47.289651,-2.192545%7C47.263097,-2.343264%7C47.261684,-2.421048

**Comment by ghost** [comment]
Airbnb validé, du coup je mets l'adresse d'arrivée exacte et ça donne ça : 
https://www.geovelo.fr/nantes/itinerary/search?profile=MEDIAN&bikeType=TRADITIONAL&wayPoints=47.256023,-1.524675%7C47.199861,-1.573877%7C47.195253,-1.581452%7C47.194145,-1.676102%7C47.261728,-1.786737%7C47.31721,-1.943851%7C47.306735,-1.97196%7C47.309238,-1.984041%7C47.310082,-1.985435%7C47.317763,-2.007236%7C47.316017,-2.075043%7C47.303913,-2.164307%7C47.302006,-2.171838%7C47.299475,-2.181365%7C47.289651,-2.192545%7C47.263097,-2.343264%7C47.261684,-2.421048%7C47.260973,-2.420837
