### ISSUE TITLE
[Jour1/45alternatif] Chambord or not Chambord

### ISSUE THREAD

**Issue by slequeux** [manuqcr/loire_velo#2]
Perso je préfère passer par Chambord, 
- c'est plutôt joli
- Seulement 7km de plus

On pourra faire une pause au niveau du Château ou dans la foret autour. Par contre, ça peut être cool de préparer les 2 GPX compilés pour que je les charge dans le téléphone si on sent que la fatigue ou le temps va compter

**Comment by EQuincerot** [comment]
Hmm on passe par Chambord, j'ai mis justement une verrue au trajet pour aller jusqu'au château.
Juste pour être sûr, tu regardes bien http://umap.openstreetmap.fr/fr/map/la-loire-a-velo_156247 ?
Après je n'ai pas mis un itinéraire tout autour du château parce qu'on peut avoir un peu de liberté pour faire un tour et regarder ce qui nous tente dans le coin.
Et si on semble éviter Chambord, c'est pour passer par les pistes cycables.

**Comment by slequeux** [comment]
Je suis OK pour le trajet que tu fournis.
Je précise juste qu'il faudra préparer les deux trajets au cas où on sente que ça passe pas le détour niveau timing ou fatigue.

**Comment by ghost** [comment]
Ok ! (fausse manip pour le close issue)

**Comment by ghost** [comment]
Idem que #1 : 45 alternatif n'est pas notre parcours. Regarde le 45 ou le parcours final sur openstreetmap, je te laisse fermer après.

**Comment by slequeux** [comment]
Faire un trajet alternatif pour jour 1 tout entier, qui soit court et qui ne soit que dans le téléphone

**Comment by slequeux** [comment]
Il suffit de fusionner : 
https://www.geovelo.fr/orleans/itinerary/search?profile=MEDIAN&bikeType=TRADITIONAL&wayPoints=47.926702,1.906672%7C47.897758,1.904154
https://www.geovelo.fr/france/rides/324/La-Loire-%C3%A0-v%C3%A9lo-Etape-7
https://www.geovelo.fr/france/rides/325/La-Loire-%C3%A0-v%C3%A9lo-Etape-8
https://www.geovelo.fr/france/rides/38/La-Loire-%C3%A0-v%C3%A9lo-Etape-9
