### ISSUE TITLE
[Jour1/46] Détour

### ISSUE THREAD

**Issue by slequeux** [manuqcr/loire_velo#3]
on ne s'éloigne pas un poil trop de la Loire ?
En plus, si on reste proche Loire, ça ferait un peu moins de distance :)

**Comment by EQuincerot** [comment]
Il s'agît de l'itinéraire officiel, qui doit être aménagé : 
https://www.eurovelo6-france.com/etapes/blois-chaumont-sur-loire

**Comment by slequeux** [comment]
ok, dans ce cas, on suit l'officiel :)
