### ISSUE TITLE
[Jour2/48] château Amboise

### ISSUE THREAD

**Issue by slequeux** [manuqcr/loire_velo#4]
Si tu veux une photo sympa pour le château d'Amboise, il faudrait qu'on aille sur l'île au milieu (donc traverser) quitte a revenir 200m sur nos pas.

**Comment by EQuincerot** [comment]
Yep, ce que je propose, c'est de mettre un point de repère sur la carte, comme ça ma montre nous préviendra qu'il y a ça, on suivra les indications touristiques et on ira. Après l'itinéraire officiel reste le même, pour un détour de 200m, je ne pense pas qu'il soit nécessaire de faire une modification du parcours.
Ça te va comme ça ?

**Comment by slequeux** [comment]
Ok
