### ISSUE TITLE
[Jour2] Fin de journée

### ISSUE THREAD

**Issue by slequeux** [manuqcr/loire_velo#5]
Vu que ça fait "que" 50 km, je propose qu'on se pose dans le vieux tours à la fin avant d'aller rejoindre Cyril. De mémoire, il est dans la partie nord de tours, donc y'aura une grosse montée pour terminer la journée :)

**Comment by EQuincerot** [comment]
Yep, ça me va très bien. Mais tu as l'air de bien connaître. En impro une fois sur place ? :)

**Comment by slequeux** [comment]
ok, et oui, je connais plutôt bien ^^
