### ISSUE TITLE
[Jour3/51] Langeais

### ISSUE THREAD

**Issue by slequeux** [manuqcr/loire_velo#6]
Si tu veux faire un mini détour, on va passer pas loin du château de Langeais (ou j'ai vévu toute mon enfance), et ce château est très joli de l'extérieur, donc on peut prendre un verre par là

**Comment by EQuincerot** [comment]
Carrément ! Idem, je propose de marquer une étape à ce point, et de faire le détour tranquillement en impro.

**Comment by slequeux** [comment]
donc pas besoin de mise à jour du GPX ?

**Comment by ghost** [comment]
Nope je prévois ceci : 
* marquer les points d'intérêts par lesquels on veut passer sur umap
* lorsque tous les parcours sont prêts, les transférer sur movescount, et ajouter ces points aussi dans movescount

**Comment by ghost** [comment]
Action à faire : ajouter tous les lieux d'intérêt dans uMap

**Comment by ghost** [comment]
Fait
