### ISSUE TITLE
[Jour3/52] Point de départ

### ISSUE THREAD

**Issue by slequeux** [manuqcr/loire_velo#7]
J'ai l'impression que la journée ne commence pas là où se termine le 51.

**Comment by EQuincerot** [comment]
Indeed : http://umap.openstreetmap.fr/fr/map/la-loire-a-velo_156247#14/47.2526/0.2777
On voit la ligne droite de passage brutal d'un itinéraire à l'autre.
NE PAS reprendre le 52 (il est bizarre) : https://www.eurovelo6-france.com/etapes/rigny-usse-candes-st-martin
Et traiter en même temps le retour #8
