### ISSUE TITLE
[Jour3/52-53] Détour

### ISSUE THREAD

**Issue by slequeux** [manuqcr/loire_velo#8]
Je verrai plutôt quelque chose de plus court style https://www.google.fr/maps/dir/47.2609948,0.2878897/47.2091285,0.0779722/47.1802157,0.0449037/47.1301695,-0.1493172/47.1666314,-0.2145585/@47.2229753,-0.0636697,11.5z/data=!4m2!4m1!3e1 

C'est déjà notre plus grosse journée. Et tel qu'il est fait là, j'ai peur que ce soit pas super sympathique comme trajet. Avec la version que je donne on aurait pas loin de la moitié en bord de Loire

Par contre, je confirme, il faut passer par le centre ville de Montreuil-Bellay, c'est bien joli !

**Comment by EQuincerot** [comment]
L'idée était de passer par Chinon qui a l'air sympa et est une ville quand même bien connue ;-)
Mais c'est négociable !
Tu préfères le bord de Loire ?
Je traiterai le #7 au passage.

**Comment by slequeux** [comment]
ok pour Chinon
