### ISSUE TITLE
[Jour4/56-57] Centre ville Angers

### ISSUE THREAD

**Issue by slequeux** [manuqcr/loire_velo#9]
Alternative : passer par le sud d'Angers, puis saint Georges sur Loire et remonter.

**Comment by EQuincerot** [comment]
## Sans passer par le sud d'Angers
ça a l'air de faire en gros 38 bornes
## En passant par le sud d'Angers
* 44km par st georges sur loire : 
https://www.geovelo.fr/france/itinerary/search?profile=MEDIAN&bikeType=TRADITIONAL&wayPoints=47.419503,-0.435102%7C47.422067,-0.60973%7C47.408813,-0.760619%7C47.503413,-0.80139
* 37km sans passer par St Georges sur Loire : 
https://www.geovelo.fr/france/itinerary/search?profile=MEDIAN&bikeType=TRADITIONAL&wayPoints=47.419503,-0.435102%7C47.422067,-0.60973%7C47.503413,-0.80139

## Bilan
on prend le dernier itinéraire ?

**Comment by slequeux** [comment]
Par le dernier itinéraire, on aura du bord de Loire
Par Angers, on aura le centre ville d'Angers, soit de quoi faire une pause tranquille et passer au niveau du château et du lac de maine.

Au final, je pense que ce que tu proposais est mieux

**Comment by ghost** [comment]
Ok => close ?
